logLevel: debug
logFormat: console
dryRun: true

source:
  filters:
    - jmespath: "obj.metadata.namespace == 'kube-system'"

  registries:
    dockerio:
      username:
      password:

target:
  type: aws
  registry:
    aws:
      accountId: 855460960717
      region: ap-southeast-2
    dockerio:
    quayio:
