repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 38b88246ccc552bffaaf54259d064beeee434539 # v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix']
    exclude: package-lock.json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: 'hack/charts/.*\.yaml'
  - id: detect-private-key
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: end-of-file-fixer
  - id: mixed-line-ending
#- repo: https://github.com/thlorenz/doctoc
#  rev: v2.0.0
#  hooks:
#  - id: doctoc
#    args: ['--title', '## Table of Contents']
- repo:  https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
    - id: golangci-lint
      args: ['--timeout', '5m']
- repo:  https://github.com/dnephin/pre-commit-golang
  rev: ac0f6582d2484b3aa90b05d568e70f9f3c1374c7 # v0.0.17
  hooks:
    - id: go-mod-tidy
    - id: go-fmt
    - id: go-imports
