on:
  issue_comment:
    types: [created]

jobs:
  awaiting_reply:
    runs-on: ubuntu-latest
    name: Toggle label upon reply
    steps:
      - name: Toggle label
        uses: jd-0001/gh-action-toggle-awaiting-reply-label@v2.1.2
        with:
          label: awaiting-reply
          exclude-members: estahn
