name: Release
on: [workflow_dispatch]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2.4.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Run semantic-release
      run: npx -p @semantic-release/changelog -p semantic-release@17.3.0 -p @semantic-release/git semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ^1.16.5
      id: go

    - name: Login to github registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.7.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
