name: Release
on:
  workflow_dispatch:
    inputs:
      forRef:
        description: 'Branch, SHA or Tag to release'
        required: false
        type: string
  # Release patches and secruity updates on a schedule
  schedule:
    - cron: "0 0 1 * *"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        ref: ${{ inputs.forRef }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci

    - name: Unshallow
      run: git fetch --prune --unshallow

    - run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.CR_PAT }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        ref: ${{ inputs.forRef }}

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Ensure release-notes exists
      run: touch /tmp/release-notes.md

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    - name: Login to github registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.1.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
