name: Release
on:
  workflow_dispatch:
  # Release patches and secruity updates on a schedule
  schedule:
    - cron: "0 0 1 * *"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v3.4.1

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Run semantic-release
      run: npx -p @semantic-release/changelog@v5.0.1 -p semantic-release@17.3.0 -p @semantic-release/git@v9.0.1 semantic-release
      env:
        GH_TOKEN: ${{ secrets.CR_PAT }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    - name: Login to github registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.1.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
